### ISSUE TITLE
Login popup not closing, unable to use 

### ISSUE THREAD

**Issue by royaldevbrat** [heliomarpm/udemy-downloader-gui#66] opened 2022-08-04 18:36 UTC
### Udeler | Udemy Course Downloader

1.8.2

### Running as Business Account

- [ ] Yes

### Steps to reproduce

Install 1.8.2 version - mac
login with a personal udemy account
 

### ✔️ Expected Behavior

login pop should get closed automatically

### ❌ Actual Behavior

login pop does not get closed automatically

<img width="540" alt="Screenshot 2022-08-04 at 11 58 56 PM" src="https://user-images.githubusercontent.com/3677263/182927174-f1aa9c4c-93cf-4757-8cdd-3cb4c22d2f8c.png">

**Comment by heliomarpm** [comment] 2022-08-06 02:34
Sorry, Udemy modified the login mode, this has already been fixed in higher versions for Windows.
Unfortunately I can't generate versions for Mac, so far without any collaborator to generate the applications for Mac and Linux

**Comment by jawad-r3** [comment] 2022-11-20 06:27
Its happening again on Windows. Which version i can use ?

**Comment by heliomarpm** [comment] 2022-12-05 02:01
@jawad-r3 use the last version, please

**Comment by sefaorucoglu** [comment] 2022-12-11 18:02
I have same bug in last version for windows.
So i think we need one more last version.
Or have we any other potential solution?

**Comment by heliomarpm** [comment] 2022-12-12 13:03
What's your mistake?
Connecting with username and password or by token has worked for me!
Access via the social network is failing and I don't have a plan to resolve this, as the cause of the error has not yet been identified.

**Comment by heliomarpm** [comment] 2023-03-07 20:05
resolved

**Closed by heliomarpm** 2023-03-07 20:05 UTC
Labels: bug, help wanted
