### ISSUE TITLE
New Bug - Stuck on Building Course Data

### ISSUE THREAD

**Issue by Cm13my** [heliomarpm/udemy-downloader-gui#16] opened 2022-01-05 09:56 UTC
Stuck on Building Course Data
Tried VPN
Proxy, socks 5
Changed PC hwid
tried everything

also deleted cookies, etc, still not working
tried changing account

Please Help

**Comment by heliomarpm** [comment] 2022-01-07 20:07
Tried with the latest version 1.10.3?

**Comment by MarcVCE** [comment] 2022-01-07 23:16
Yes

**Comment by contracode** [comment] 2022-01-12 14:49
Confirming the same issue and fix that @joejordan posted. Thank you, @joejordan!

**Comment by heliomarpm** [comment] 2022-01-16 21:38
Please let me know which course you have with this problem

**Comment by contracode** [comment] 2022-01-16 22:21
@heliomarpm "NATRON The FREE robust alternative to NUKE & AFTER EFFECTS" had this issue.

**Comment by heliomarpm** [comment] 2022-01-30 18:28
Duplicate of #12

**Closed by heliomarpm** 2022-01-30 18:28 UTC
Labels: bug
