### ISSUE TITLE
Issue with Downloading "ENOENT: no such file or directory, unlink"

### ISSUE THREAD

**Issue by Manfrad** [heliomarpm/udemy-downloader-gui#127] opened 2023-05-16 14:24 UTC
Hi there

Thank You for this super utility.

May I submit a problem statement:

When downloading courses, the download fails with a video item and then stops,
* i.e., does not continue with the next lectures.
* If there is an error, the whole process stops, regardless if this was the 2nd, 3rd, ... lecture.

It throws two error messages.
The error messages are (without the separating lines):
---------------------------------------------------------------------------------------
errorDownload
Error: ENOENT: no such file or directory, unlink 'C:\1\Statistical Process Control (SPC) Using Microsoft Excel\1. Introduction\4. Data Scales.mp4'

errorDownload
The .mtd file is corrupt. Start a new download.
---------------------------------------------------------------------------------------

Result:
* directories are created successfully.
* .mtd file is created, always with size of 0 byte.

Activities:
- deinstall 1.12.4
- reinstall 1.12.4
- using portable 1.12.4
- checking access control on the files created
- checking multiple courses, some fail, some not
- counting 256 max length
- starting with different lectures in "Settings"
- choosing different video quality in "Settings"
- choosing only videos to download in "Settings"
-

**Comment by heliomarpm** [comment] 2023-05-16 18:29
Hello, normally the ENOENT error is related to permission, and I believe the cause is the .mtd file.

When that happens, follow these steps:
Close Udeler
Delete the .mtd file
Restart the download.

You can also leave the option "Auto Retry on Error (Experimental)" checked in the settings section.

**Comment by Manfrad** [comment] 2023-05-17 05:06
Hi there

Thank You very much for Your quick reply.

* Followed Your instructions.
* Also ran Udeler with Administrator privileges (concerning the permission hint)
* "Auto Retry on Error (Experimental)" switched on.

-> I encountered the same behaviour (with any account)

Stops the entire process.

I noticed you already classified this as "bug", so please consider this as additional input.

If You wanted a video or anything, pls let me know.

**Comment by Manfrad** [comment] 2023-05-17 05:40
Hi there

May I provide additional information with these error codes:

Two well known, but one additional new with more extensive information.

-----------------------------------------------------------------------------------------------
errorDownload
Error: ENOENT: no such file or directory, unlink 'C:\1\Der Komplette Excel Kurs - Vom Anfänger zum Profi in 50h\1. Der Komplette Excel Kurs - Von der ersten Formel zum Expertenstatus\2. Zertifikat, Downloads und Rechnungen.mp4'

errorDownload
Invalid file path: C:\1/Der Komplette Excel Kurs - Vom Anfänger zum Profi in 50h/1. Der Komplette Excel Kurs - Von der ersten Formel zum Expertenstatus/2. Zertifikat, Downloads und Rechnungen.mp4.mtd

errorDownload
Error: ENOENT: no such file or directory, unlink 'C:\1\Der Komplette Excel Kurs - Vom Anfänger zum Profi in 50h\1. Der Komplette Excel Kurs - Von der ersten Formel zum Expertenstatus\2. Zertifikat, Downloads und Rechnungen.mp4'

errorDownload
The .mtd file is corrupt. Start a new download.

uncaughtException
Error: ENOENT: no such file or directory, unlink 'C:\1/Der Komplette Excel Kurs - Vom Anfänger zum Profi in 50h/1. Der Komplette Excel Kurs - Von der ersten Formel zum Expertenstatus/1. Herzlich Willkommen im Kurs. Schön, dass du da bist!.vtt' at Object.unlinkSync (fs.js:1140:3) at WriteStream. (file:///C:/Users/chr.009.400/AppData/Local/Programs/udeler/resources/app.asar/app/app.js:1117:16) at WriteStream.emit (events.js:327:22) at finishMaybe (_stream_writable.js:639:14) at _stream_writable.js:616:5 at WriteStream._final (internal/fs/streams.js:352:3) at callFinal (_stream_writable.js:609:10) at processTicksAndRejections (internal/process/task_queues.js:84:21)
-----------------------------------------------------------------------------------------------

Thank You!
Markus

**Comment by tejastg007** [comment] 2023-05-17 19:45
The same problem is arising with me.
Is it because of udemy's encryption?

**Comment by tejastg007** [comment] 2023-05-17 20:07
got below line on the windows terminal-
(node:14108) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead

**Comment by entrysky** [comment] 2023-05-19 08:50
hello all, any solution for this
i have same error: errorDownload
The .mtd file is corrupt. Start a new download.
thank you!

**Comment by heliomarpm** [comment] 2023-05-19 19:49
> hello all, any solution for this i have same error: errorDownload The .mtd file is corrupt. Start a new download. thank you!

https://github.com/heliomarpm/udemy-downloader-gui/issues/127#issuecomment-1550163283

**Comment by heliomarpm** [comment] 2023-05-19 19:51
> The same problem is arising with me. Is it because of udemy's encryption?

I don't think this problem is only related to the protected videos, I think it's a problem with the download library itself, I'm evaluating new libraries

**Comment by zhaoTimer** [comment] 2023-05-22 03:20
hi! same question, 

- windows x64 
- v1.12.4
- udemy personal plan
- the 1st lesson video is downloaded completely, the following cannot be done

Here are some debugging logs，sry about my weak js to help work out

![Snipaste_2023-05-22_11-11-02](https://github.com/heliomarpm/udemy-downloader-gui/assets/75229705/cd90593c-94b3-45bc-98ef-f28b995eb50d)
![Snipaste_2023-05-22_11-17-05](https://github.com/heliomarpm/udemy-downloader-gui/assets/75229705/56d390f0-85e3-4914-8962-d8c8e32a52ff)

**Comment by heliomarpm** [comment] 2023-05-22 23:29
> hi! same question, 
> 
> - windows x64 
> - v1.12.4
> - udemy personal plan
> - the 1st lesson video is downloaded completely, the following cannot be done
> 
> Here are some debugging logs，sry about my weak js to help work out
> 
> ![Snipaste_2023-05-22_11-11-02](https://github.com/heliomarpm/udemy-downloader-gui/assets/75229705/cd90593c-94b3-45bc-98ef-f28b995eb50d)
> ![Snipaste_2023-05-22_11-17-05](https://github.com/heliomarpm/udemy-downloader-gui/assets/75229705/56d390f0-85e3-4914-8962-d8c8e32a52ff)
> 

It seems to me that this course is protected, if so it cannot be downloaded.  Anyway, if that's the problem, the error message should be something else.  I will check

**Comment by snikolay** [comment] 2023-05-23 06:41
Same error too, downloaded only the first video, on the next error, used the start/end function to skip the video, it doesn't want to download any next.

**Comment by heliomarpm** [comment] 2023-05-26 19:53
check new version 
https://github.com/heliomarpm/udemy-downloader-gui/releases/tag/v1.12.5

**Closed by heliomarpm** 2023-05-26 19:53 UTC
Labels: bug
